### ISSUE TITLE
Purpose of GetName

### ISSUE THREAD

**Issue by gptucci** [mrpmorris/blazor-fluxor#100]
Hi
What is the purpose of GetName in Feature ??
I've reade docu but.....

Tnx and excuse me for question

**Comment by mrpmorris** [comment]
If you run the redux middleware demo and look at the persisted state you'll see all features are combined as a super-state using the feature name as a property name. The name is used when deserializing the state back into the store when viewing different historical states in the Redux DevTools browser extension.
