### ISSUE TITLE
FluxorComponent using OwningComponentBase instead of ComponentBase?

### ISSUE THREAD

**Issue by fnils** [mrpmorris/blazor-fluxor#101]
Would it be possible with a version or change to OwningComponentBase instead of ComponentBase?
Then it would be possible to use ScopedServices, where needed, as mentioned in the article in the link below.

https://chrissainty.com/an-introduction-to-owningcomponentbase/

**Comment by fnils** [comment]
A character went missing.

**Comment by mrpmorris** [comment]
You don't need to descend from FluxorComponent. You can just do SomeState.Subscribe(this) in your OnInitialized
