### ISSUE TITLE
How to react to an action in the component context?

### ISSUE THREAD

**Issue by nstohler** [mrpmorris/blazor-fluxor#102]
I have component that dispatches a `IncrementCounterAction`, which has an effect method that (simulates) incrementing the counter on the server via http and dispatches then `IncrementCounterSuccessAction` or `IncrementCounterFailedAction`. Those have their own reducer actions which create the new states. This works all as expected. 

Now back in the Blazor component that originally dispatched the `IncrementCounterAction`, I want to react to those success/failed actions **in the component context**. This makes not much sense in this very simple example here, but in a component with a form, after successfully posting the form data to the server I might want to clear the form and maybe show a toast message. 

I've added an effect handler to the Blazor component:
```
[EffectMethod]
public async Task HandleAsync(IncrementCounterSuccessAction action, IDispatcher dispatcher)
{
	Console.WriteLine($"IncrementCounterSuccessAction effect @ BlazorFluxor.razor.cs {action.ServerCount}");
	this.addTodo = new TodoDto(); // trying to clear the form data
}
```

Some notes:
- the handler gets called, but it's not in the component context. I'm using a Blazor-Code-Behind class, so I guess that one just gets newed up again. 
- above version gets called **twice**
- if I make the method **static**, it only gets called once
- the form doesn't get cleared

I know there is `StateChanged` even, but then I need to keep track of some state values in the component and compare those to determine which action need to react to. Also I don't like the idea to duplicate some state values just for this. 

Or is there another simple, clean way I'm not seeing right now?

**Comment by nstohler** [comment]
I've juggled around with this some more, one way that works is if I extend `IncrementCounterAction` / `IncrementCounterSuccessAction` like this:

```
using System.Text.Json.Serialization; // NOT Newtonsoft.Json!

public class IncrementCounterAction
{
	public IncrementCounterAction(int prevCount, Action successAction = null	)
	{
		SuccessAction = successAction;
		PrevCount     = prevCount;
	}

	public int PrevCount { get; private set; }

	[JsonIgnore] // for ReduxDevToolsMiddleware to not serialize this
	public Action SuccessAction { get; private set; }
}

public class IncrementCounterSuccessAction
{
	public IncrementCounterSuccessAction(int serverCount, Action successAction)
	{
		ServerCount = serverCount;
		SuccessAction = successAction;
	}

	public int ServerCount { get; private set; }

	[JsonIgnore] // for ReduxDevToolsMiddleware to not serialize this
	public Action SuccessAction { get; private set; }
}
```

Then I can dispatch the action from the `Blazor component`:

```
Dispatcher.Dispatch(new IncrementCounterAction(CounterState.Value.CurrentCount,
	() =>
	{
		Console.WriteLine($"DoneAction @ BlazorFluxor.razor.cs");

		ClearAddForm();
		StateHasChanged();
	}
	));
```

The effect method for `IncrementCounterAction` forwards the action to `IncrementCounterSuccessAction`, where the action the gets invoked.
```
[EffectMethod]
public async Task HandleAsync(IncrementCounterAction action, IDispatcher dispatcher)
{
	try
	{
		Console.WriteLine("CounterEffect IncrementCounterAction");
		await Task.Delay(500);

		dispatcher.Dispatch(new IncrementCounterSuccessAction(action.PrevCount + 1, action.SuccessAction));
	}
	catch (Exception e)
	{
		dispatcher.Dispatch(new IncrementCounterFailedAction("simulated http fetch failed somehow"));
	}
}

[EffectMethod]
public Task HandleAsync(IncrementCounterSuccessAction action, IDispatcher dispatcher)
{
	Console.WriteLine("CounterEffect IncrementCounterSuccessAction");
	action.SuccessAction?.Invoke();

	return Task.CompletedTask;
}

```
This works now (after incrementing the counter, the form gets cleared), BUT of course it's not nice to bloat the action classes with `Action`s only for some sort of callback. 

But maybe the `Dispatch` method could be extended to handle all the above (react to specific actions) in an elegant way?

**Comment by mrpmorris** [comment]
It can be made more simple. I would recommend that in the reducer for the successful action you dispatch as a result of the server request you set a new LastSuccessfulPostTime in your state to DateTime.UtcNow. In your component you can store that value from in OnInitialized and then you could override ShouldRender() on your component and if the new state.LastSuccessfulPostTime has changed the store the new value in your component and clear the form.

PS: You could also have a single action that is triggered after the effect with a boolean Successful flag rather than having to have both a successful and fail action.

**Comment by nstohler** [comment]
I've also found this older issue here https://github.com/mrpmorris/blazor-fluxor/issues/43 and added the code from https://github.com/Gaulomatic/Logixware.AspNet.Blazor.Fluxor (with some slight changes to make it work with the current version of  Blazor-Fluxor https://github.com/Gaulomatic/Logixware.AspNet.Blazor.Fluxor/issues/1).

With this, I don't need to add any `Action`s to my action classes, I can just subscribe to `IncrementCounterSuccessAction` in `OnInitialized()` of my Blazor component:

```
public class BlazorFluxorBase : FluxorComponent, IDisposable
{
	[Inject] protected IDispatcher Dispatcher { get; set; }
	[Inject] protected IState<ICounterState> CounterState { get; set; }	
	[Inject] protected IObservableStore ObservableStore { get; set; }

	private List<IDisposable> _subscriptions = new List<IDisposable>();

	protected override void OnInitialized()
	{
		base.OnInitialized();

		var sub = this.ObservableStore.Actions
			.TakeAction<IncrementCounterSuccessAction>()
			.Subscribe(action =>
			{
				Console.WriteLine($"ObservableStore.Actions for IncrementCounterSuccessAction @ BlazorFluxor.razor.cs | counter is {CounterState.Value.CurrentCount} / {action.ServerCount}");
				this.ClearAddForm();
				base.StateHasChanged();
			});

		_subscriptions.Add(sub); // just a list to be able to unsubscribe later	
	}
	
	protected void IncrementCount()
	{
		Dispatcher.Dispatch(new IncrementCounterAction(CounterState.Value.CurrentCount));
	}

	public void Dispose()
	{	
		foreach (var subscription in _subscriptions)
		{
			subscription.Dispose();
		}
	}	
}
```

**Comment by nstohler** [comment]
> It can be made more simple. I would recommend that in the reducer for the successful action you dispatch as a result of the server request you set a new LastSuccessfulPostTime in your state to DateTime.UtcNow. In your component you can store that value from in OnInitialized and then you could override ShouldRender() on your component and if the new state.LastSuccessfulPostTime has changed the store the new value in your component and clear the form.
> 
> PS: You could also have a single action that is triggered after the effect with a boolean Successful flag rather than having to have both a successful and fail action.

Thanks, I will look into this next
