### ISSUE TITLE
How to call Dispatcher from a .cs-file?

### ISSUE THREAD

**Issue by Syltis** [mrpmorris/blazor-fluxor#105]
Hi!

One thing I could not find anything on in your examples is how to call the IDispatcher from a .cs-file. I would like to move the action-calls to services and call the services from the .razor-pages. 

Sadly I am not able to inject IDispatcher as a service for use in classes. In the .razor files, '@inject' is used, but doing constructor-injection in a .cs-class causes a stack-overflow error. Am I missing something here? I understand this might be simply asking for help, not an issue, but I guess the issue here is that it doesn't say how to do it anywhere in the otherwise great examples.

**Comment by Syltis** [comment]
*I think an easier wording of my question is; how to access the store in a .cs class?

**Comment by mrpmorris** [comment]
If you look at the generated CS file for a component you'll see that `@Inject` results in a line like this

```
[Inject]
private IJSRuntime JSRuntime { get; set; }
```

You should be able to inject what you need that way.

**Comment by Gaulomatic** [comment]
If your class is not an inheritor of `Component` (meaning it's a plain C# class), you use constructor injection; the DI container will handle the rest. The catch is, you have to register your class to the DI container as well.
