### ISSUE TITLE
Building and referencing Blazor.Fluxor

### ISSUE THREAD

**Issue by nstohler** [mrpmorris/blazor-fluxor#109]
I'm trying to extend Blazor-Fluxor and am running into problems when referencing my custom built `Blazor.Fluxor.dll` from my demo project. I'm getting the errors described here:
https://github.com/mrpmorris/blazor-fluxor/issues/98

```
Unhandled exception. Blazor.Fluxor.Exceptions.StoreInitializationException: Store initialization error
 ---> Microsoft.JSInterop.JSException: Could not find 'tryInitializeFluxor' in 'window'.
...
```

To reproduce in the original Blazor.Fluxor repo:
- build the Blazor.Fluxor project
- In Samples/CounterSample:
  - remove the project reference to Blazor.Fluxor
  - add an assembly reference to the built `Blazor.Fluxor.dll`:  
`..\..\..\src\Blazor.Fluxor\bin\Debug\netstandard2.1\Blazor.Fluxor.dll`
  - try to run the CounterSample

I compared the bin output when building the CounterSample and found that it contains a `CounterSample.StaticWebAssets.xml` (when building with a project reference). This file is not there when building with the assembly reference. When I just backup the file and copy it into the `bin\Debug\netcoreapp3.1` dir, the assembly referencing works as well. 

But I have no idea why that is so. What am I missing?

CounterSample.StaticWebAssets.xml contents:
```
<StaticWebAssets Version="1.0">
  <ContentRoot BasePath="_content/Blazor.Fluxor" Path="C:\Git\demos\blazor-fluxor\src\Blazor.Fluxor\wwwroot\" />
</StaticWebAssets>
```

Just to be complete: referencing the Nuget package directly works too.

**Comment by mrpmorris** [comment]
Add a project reference instead of referencing the build output directly. Does that help?

**Comment by mrpmorris** [comment]
Sorry, accidentally closed the issue.

**Comment by mrpmorris** [comment]
Is it okay for me to close this issue?

**Comment by nstohler** [comment]
I didn't have time to investigate this further, will do so later
