### ISSUE TITLE
Implementation when UI / Store is stored in another project

### ISSUE THREAD

**Issue by enkodellc** [mrpmorris/blazor-fluxor#115]
@mrpmorris  I am newbie to Redux / Fluxor and manage Blazor Boilerplate. One of my users wants to use Blazor.Fluxor and my new version allow for both CSB and SSB so he has an issue when migrating. Our new version separates the UI into a common project so the user can then choose CSB or SSB and it runs. I am not sure if this will work with Blazor.Fluxor and if it does I don't know how to make it work and neither does he at this time.

> blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
> h.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM: System.InvalidOperationException: Unable to resolve service for type 'Blazor.Fluxor.IFeature`1[BlazorBoilerplate.CommonUI.FlightFinder.Store.AppState]' while attempting to activate 'Blazor.Fluxor.State`1[BlazorBoilerplate.CommonUI.FlightFinder.Store.AppState]'.

I created a branch for you to take a look and maybe give your opinion on how it needs to be structured. The app runs but when you go to the _/flightfinder_ page it errors if I include the store.
I suspect it is because the project has some issues from not being in startup? This is the only page I have used a store and it is all taken from your FlightFinder example but changed namespace to use with Blazor Boilerplate.   

https://github.com/enkodellc/blazorboilerplate/tree/blazorfluxor

Thanks,

**Comment by soomon** [comment]
@mrpmorris I am the user :D 
I started using blazor-fluxor and it worked well! Thanks for sharing this great library!
In the old version of Blazor Boilerplate I included blazor-fluxor in startup.cs of the client project. 
All files related to the store were within the client project. That worked well.

Now that BB features Client Side Blazor and Server Side Blazor within one project template, which is awesome, we receive the error mentioned above although I tried adding the code for Blazor-Fluxor to both the client's and the server's Startup.cs file.
As you can see from the branch @enkodellc generously created, all UI related files are stored in a separate project called CommonUI which is used by Server Side Blazor and Client Side Blazor.
This seems to break Blazor-Fluxor :/

I would greatly appreciate it if you could take the time to look at this issue.
Blazor Boilerplate in my view is the best Blazor template out there and @enkodellc is investing a lot of time to improve it. It would be awesome to have Blazor-Fluxor working with it.

Thanks a lot!
Cheers,
soomon

**Comment by mrpmorris** [comment]
Hi

https://github.com/enkodellc/blazorboilerplate/blob/blazorfluxor/src/BlazorBoilerplate.Client/Startup.cs#L46

When you add fluxor you need to provide one or more assemblies to scan. You are scanning the current assembly rather than the assembly where your features and reducers are. 

Try changing `typeof(Startup).Assembly` to `typeof(OneOfYourFeatures).Assembly`,that should do it.

**Comment by soomon** [comment]
I tried it using:

```
            services.AddFluxor(options =>
            {
                options.UseDependencyInjection(typeof(ProjMan.CommonUI.Store.Projects.ProjectsFeature).Assembly);
                options.AddMiddleware<ReduxDevToolsMiddleware>();
                options.AddMiddleware<RoutingMiddleware>();
            });
```

The error is gone but the store does not get created. 

I see some notes in the console:
WASM: Error LoadData: Value cannot be null.
blazor.webassembly.js:1 WASM: Parameter name: source
blazor.webassembly.js:1 WASM: Error LoadData: Value cannot be null.
blazor.webassembly.js:1 WASM: Parameter name: source

No store gets created. No requests to the server are made.
Am I missing something?
Thanks again!

**Comment by mrpmorris** [comment]
Do you have something you can share with me privately?

**Comment by soomon** [comment]
This issue has been solved by @mrpmorris . Thanks again!
