### ISSUE TITLE
Collection was modified after the enumerator was instantiated.

### ISSUE THREAD

**Issue by hybrid-technologies-solutions** [mrpmorris/blazor-fluxor#117]
I know it will be very hard to debug because it seems to be linked in a race condition within my code.

I encounter this exception when calling Dispatch on a dispatcher instance when some tasks are processing in parallel.

This is the Stacktrace : 

```
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Blazor.Fluxor.Store.DequeueActions()
   at Blazor.Fluxor.Store.Dispatch(Object action)
   at HTS_Account.UI.Store.Profile.Effects.GetProfileDataEffect.<HandleAsync>d__2.MoveNext() in D:\repos\HTS_Account\src\HTS_Account.UI\Store\Profile\Effects\GetProfileDataEffect.cs
```

My guess is using the `Count `property on Queue instead of calling `Any()` should resolve this (and it should be more performant as well)

**Comment by mrpmorris** [comment]
You shouldn't dispatch tasks in parallel, the library doesn't have any multi-thread sync in it.

Why are you doing that?

**Comment by hybrid-technologies-solutions** [comment]
Because my GUI is composed of a set of independant component that load data asynchronously in a background worker. And sometimes, I can have a race condition if some task are dispatch from my background worker and when the user browse to a subsection that needs a dispatch.

Are you planning to implements multi-thread sync or not at all ?

**Comment by mrpmorris** [comment]
I think it wouldn't be much work

**Comment by mrpmorris** [comment]
Could you check out the source to this repo (branch PeteM/ThreadSafe) and give it a try with your app?

**Comment by mrpmorris** [comment]
Note: This branch was last updated yesterday, so if you have pulled already then you'll need to pull the latest changes @hybrid-technologies-solutions
