### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by DocTi** [mrpmorris/blazor-fluxor#119]
An exception in `JavaScriptStoreInitializationStrategy` on line 64 causes the application to crash.

I got the exception "A task was canceled". It can be obtained if one of the clients very often refreshes the browser page, and then closes it afterwards.

`success = await JSRuntime.InvokeAsync<bool>("tryInitializeFluxor");` due to interruption of this task internally when the connection timed out.

**Comment by DocTi** [comment]
Blazor.Fluxor.Exceptions.StoreInitializationException
  HResult=0x80131500
  Message=Store initialization error
  Source=Blazor.Fluxor
  StackTrace:
   at Blazor.Fluxor.JavaScriptStoreInitializationStrategy.<>c__DisplayClass2_0.<<Initialize>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

  This exception was originally thrown at this call stack:
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	Blazor.Fluxor.JavaScriptStoreInitializationStrategy.Initialize.AnonymousMethod__0(object)

Inner Exception 1:
TaskCanceledException: A task was canceled.

**Comment by mrpmorris** [comment]
What do you mean by "one of the clients"? Are you only seeing this when there are multiple client browsers running against a server-side Blazor app and they are refreshing the page?

**Comment by DocTi** [comment]
Any number of browser tabs. One of them is constantly updated (quick press F5) and close the tab. After a while, the application crashes with an error above.

**Comment by DocTi** [comment]
Occurs due to the cancellation of the task in `IJSRuntime`

**Comment by mrpmorris** [comment]
Ah, so C# on the server invokes JS in the browser but the tab has been destroyed so the task times out. Must be that. Thanks!

**Comment by frenzy10012** [comment]
Im getting the same error after couple of minutes after i start the application. How can i trace down the root of the problem? I'm using Telerik Blazor components.

**Comment by mrpmorris** [comment]
You are getting an error about tryInitializeFluxor after a number of minutes of using your app? In the same tab you've been using?

**Comment by frenzy10012** [comment]
Yes. I'm always using only one tab. Sometimes i'm getting an error after just running application for a minute and not doing anything. Till now i haven't figured out how to reproduce a problem. I get an error randomly, sometimes is working fine for hours (even days), other times fails everytime i run an application. The only pattern i found is that application crashes after couple of minutes after is being started. Maybe it would help if i mention that i'm using Visual Studio 2017 (running app in IIS express server). I haven't try application on production IIS. Do you have any idea how to trigger an error? I've tried with multi tabs but i was unable to reproduce a problem.

**Comment by DocTi** [comment]
An application crash causes any unhandled exception in the class `System.Threading.Timer`. There are two such places in the Fluxor implementation.

`Blazor.Fluxor.JavaScriptStoreInitializationStrategy `
line 64
line 72

https://github.com/mrpmorris/blazor-fluxor/blob/master/src/Blazor.Fluxor/JavaScriptStoreInitializationStrategy.cs#L64
https://github.com/mrpmorris/blazor-fluxor/blob/master/src/Blazor.Fluxor/JavaScriptStoreInitializationStrategy.cs#L72

**Comment by mrpmorris** [comment]
Can you provide me with an example + steps explaining exactly what to do to reproduce this, please?

**Comment by mrpmorris** [comment]
Are these client-side apps, or server-side?

**Comment by frenzy10012** [comment]
Sorry, i can't find the pattern to reproduce this. Its Server-Side.

**Comment by DocTi** [comment]
server-side

**Comment by frenzy10012** [comment]
Hi! With the latest version of 1.4.0 i'm still occasionally get the same error. Any ideas?

**Comment by mrpmorris** [comment]
Is it when closing tabs?

**Comment by frenzy10012** [comment]
No..just when i use application..it happens very rarerly..i can't find
pattern to reproduce..

V ned., 23. feb. 2020 10:59 je oseba Peter Morris <notifications@github.com>
napisala:

**Comment by mrpmorris** [comment]
If you check out the code, reference it directly from your app instead of referencing the Nuget packages, could you check if this stop happening if you edit `JavaScriptStoreInitializationStrategy` and add the following catch

```
catch (TaskCancelledException)
{
  return;
}
```

**Comment by frenzy10012** [comment]
I can confirm this solution is correct. I don't get 

> If you check out the code, reference it directly from your app instead of referencing the Nuget packages, could you check if this stop happening if you edit `JavaScriptStoreInitializationStrategy` and add the following catch
> 
> ```
> catch (TaskCanceledException)
> {
>   return;
> }
> ```

I can confirm this solution resolved the problem. Can you please release new version of a nuget package with this patch.

**Comment by frenzy10012** [comment]
Do you have any idea why would TaskCanceledException exception even raise? What cause this exception?

**Comment by mrpmorris** [comment]
If it is during initialization, or you have ReduxDevTools enabled then it is possibly Blazor cancelling an invokation to some JavaScript.

**Comment by mrpmorris** [comment]
Fixed in 1.4.1
