### ISSUE TITLE
Remove usage of `async void`

### ISSUE THREAD

**Issue by mrpmorris** [mrpmorris/blazor-fluxor#120]

**Comment by goodisontoffee** [comment]
Hi, I have spent a couple of hours on this issue and it is rapidly turning into a bit of a big job. Before I carry on, would you be able to put some more detail on this issue as to what you're expecting (especially in regards to how much you want to await everything that turns into being awaitable), or tell me to stand down.

I've gotten to a point where things are coming together but it's got into a deadlock state know (firing off effects as part of action dispatch handling). Happy to help but could use a bit of a steer as to what you're looking for here.

**Comment by mrpmorris** [comment]
It's certainly not going to be a simple one :)

**Comment by goodisontoffee** [comment]
I've pushed a simpler starting point to https://github.com/goodisontoffee/blazor-fluxor/tree/feature/remove-single-async-void-usage, don't keen on raising a PR as it's currently broken. Within the synchronous dispatch the effects are triggered, if those effects seek to raise actions, they are blocked by the semaphore leading to a deadlock.

**Comment by mrpmorris** [comment]
Why did you change it to a mutex?

**Comment by goodisontoffee** [comment]
We can’t await within lock.

**Comment by mrpmorris** [comment]
Here are my initial thoughts. What do you think?
https://github.com/mrpmorris/blazor-fluxor/commit/238b10d1b0254167e60a3bd342cb31c38e5798a6

**Comment by mrpmorris** [comment]
Here is my PR - https://github.com/mrpmorris/blazor-fluxor/pull/129/files - could you review it please?

**Comment by goodisontoffee** [comment]
Will do, Probably on Sunday. #hectic!

**Comment by goodisontoffee** [comment]
Found a bit of a window to take a look. Added some comments to the PR, I'm a little worried about how middlewares will react to no longer .Wait()-ing for the initialization to complete but I like the new store initialization process (via a component).
