### ISSUE TITLE
FeaturesByName dictionary tries to insert duplicate keys

### ISSUE THREAD

**Issue by ndotb** [mrpmorris/blazor-fluxor#122]
fluxor 1.4.0 master@head / blazor 3.2.0-preview1.20073.1

When going through dependency discovery and injection, some features in satellite assemblies are detected twice and throw a key violation during the catalog phase.  While the root issue is probably in DependencyScanner, this is the line causing the issue:

https://github.com/mrpmorris/blazor-fluxor/blob/78f184b380158f36fb44939724b06727e2ebf87c/src/Blazor.Fluxor/Store.cs#L60

Fix for key check outside of the lock incoming a few minutes after I open this.

**Comment by mrpmorris** [comment]
Hi

Could you make an example app that reproduces this problem?

**Comment by mrpmorris** [comment]
I'm closing this for now. I'll reopen if you submit a sample that reproduces the problem.
