### ISSUE TITLE
Why "StoreInitializer"  is not working?

### ISSUE THREAD

**Issue by univerise** [mrpmorris/blazor-fluxor#133]
Dears,

I want to have a try with blazor-fluxor, and nuget it to my demo project. But, it fails when I add Blazor.Fluxor.StoreInitializer, it says it not found.

![image](https://user-images.githubusercontent.com/14052591/75839067-ccf86d80-5e02-11ea-8154-ee1be2448513.png)

Could anyone help me?

Thanks.

**Comment by jormigo** [comment]
Seems like that's meant to be used in the 2.0 release but the current version is still 1.4.1, gotta wait until 2.0 is available on the nuget

**Comment by univerise** [comment]
Thanks @jormigo. You are corrected. I complied the project by myself and added reference with it, that works well. So the Nuget is not updated as expected.

@mrpmorris Could help re-check the nuget. Thanks. This is a good practice.

**Comment by mrpmorris** [comment]
Hi

Sorry about that. The NuGet package has now been published.
