### ISSUE TITLE
[RoutingMiddleware] issue with 3.2.0-preview2 authentication

### ISSUE THREAD

**Issue by MitchellNZ** [mrpmorris/blazor-fluxor#134]
I just recently upgraded to the new 3.2.0-preview version of Blazor and implemented the new token-based authentication they provide.

However, my app kept getting stuck in an infinite loop when redirecting from logging in.
I eventually tracked it down to being related this line in my `Program.cs`:
`.AddMiddleware<RoutingMiddleware>()`

Unfortunately, I can't provide much more details as to why, but for now I have commented that line out and there are no issues.

This can be reproduced by creating a new Blazor starter project with token-based authentication by following [this blog](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/), adding Fluxor to the project with Redux dev tools and the `RoutingMiddleware`.

Hope this helps.

**Comment by micklaw** [comment]
@MitchellNZ The hero we need

**Comment by micklaw** [comment]
@mrpmorris Hey man, just wondered why this has been closed, or if you found a resolution. I was going to have a look at try to get to the bottom of it, but if you already have I’d be keen to know what was going on there?

**Comment by mrpmorris** [comment]
Someone at work came across the same problem today. They submitted a PR, I merged and released.

There's a link against the comment that says I closed it.

**Comment by micklaw** [comment]
Awesome, thanks

**Comment by mrpmorris** [comment]
@micklaw please let me know if it works for you

**Comment by MitchellNZ** [comment]
@mrpmorris Thanks for the update!
Can confirm this is working fine for me now.

**Comment by mrpmorris** [comment]
@MitchellNZ Thanks for getting back to me!
