### ISSUE TITLE
[Question] Can we split state in multiple ones like redux  

### ISSUE THREAD

**Issue by AlexTeixeira** [mrpmorris/blazor-fluxor#135]
Hi, 

Many thanks for this nuget package, it's quite goot thing to keep Flux pattern with blazor.

I'm looking to your samples and working to implement a state in my application, but I think, the state will growth with time.

To don't have a big unmaintainable AppState, could the state be split in many other one like in Redux ?

Thank for your answer

**Comment by soomon** [comment]
Hi Alex,

yes you can have multiple states.
If you take a look at the FlightFinder example here: **https://github.com/mrpmorris/blazor-fluxor/tree/master/samples/05-FlightFinder/FlightFinder/FlightFinder.Client/Store**

You can copy the state and feature file and create new states.

I hope that answeres your question.

**Comment by AlexTeixeira** [comment]
Hi,

So if I understand, I just need to create a new State and Feature when I need to split my principal AppState ?

If is right, it seems to be the same thing as Redux, So I should not be lost ^^.

**Comment by soomon** [comment]
Yes that is correct.

**Comment by mrpmorris** [comment]
Yes, a Feature is an independent chunk of state. You can add a reducer that will clear out the state of that feature if the user navigates somewhere that is no longer relevant to the task that feature deals with. Just reduce the `Go` Action.
