### ISSUE TITLE
Fluxor Entities - Request for comments

### ISSUE THREAD

**Issue by mrpmorris** [mrpmorris/blazor-fluxor#30]
# Fluxor Entities
## Request for comments

I would like to add a way of managing the state of entities (think NGRX/Entity for Angular but less work - https://github.com/ngrx/platform/tree/master/docs/entity)

My proposal is to add a feature named `EntitiesFeature<TEntitiesState>` that you can consume in your Blazor views. The approach I wish to propose would look like this:

```c#
public class MyAppEntities
{
  // Define collections of entities, and declare the primary key
  public Entities<Person> People { get; set; } = new Entities<Person>(x => x.Id);
  public Entities<Company> Companies { get; set; } = new Entities<Company>(x => x.CompanyId);
}

public class MyAppEntitiesFeature<MyAppEntities> 
{
  public override string GetName() => "Entities"; // The name of the property in the state
}
```
You could insert / update / remove entities like this

```c#
  // Insert a person
  var person = new Person(id: 1);
  var upsertAction = new UpsertEntitiesAction(person);
  await Store.Dispatch(upsertAction);

  // Update our person, and insert a company
  person.Name = "Peter Morris";
  var company = new Company(companyId: 101776);
  upsertAction = new UpsertEntitiesAction(person, company);
  await Store.Dispatch(upsertAction);

  // Now remove the company and person
  var removeAction = new RemoveEntitiesAction(company, person);
  await Store.Dispatch(removeAction);
```
Because the Flux/Redux pattern states the store state should be immutable we shouldn't have direct access to entities, just in case their state is modified via an action.

To clarify. When the library user updates the state of a single entity, held within a collection, that belongs to state, the library should do the following:
1. Create a new instance of the entity based on the previous entity + the state change specified in the action.
2: The `Entities<T>` collection should be recreated with all previous entities in it + the new entity.
3: The `entities state` (the state of the feature) should be recreated with all the previous entity collections in it + the new collection replacing the previous one.

Here is an example of a scenario we wish to avoid:
1. Entity is upserted to the entities state.
2. A view retrieves a reference to that entity and displays it.
3. An action is executed that alters the state of the entity.
4. A copy of the entity is made with the changes specified in the action.
5: The entity is upserted to the entities state.
6: The view re-renders old state because the view has a direct reference to an entity that is no longer in the new entities state object.

Our view will never have a stale copy of the feature's state because we always access it via its `Current` property like so:
```
@inject IState<SomeFeatureState> State

<h1>Hello State.Current.Name</h1>
```

I propose using the same indirection technique for when the view requires entity references.

```
@inject IState<MyAppEntities> Entities

<h1>All Person objects</h1>
@if (Entities.People.Any()) 
{
  <ul>
    @foreach(var personRef in Entities.People) 
    {
      <li>@personRef.Entity.Name</li>
    }
  </ul>
}

<h2>Single person<h2>
@person.Entity.Id has the name @person.Entity.Name

@functions {
  EntityRef<Person> person = Entities.People.Get(12345); // Correct
  Person person2 = Entities.People.Get(12345).Entity; // Incorrect
}
```

The EntityRef is guaranteed to never change, but the entity reference it holds will always be the latest one in the `Entity<T>` collection.

### Additional benefits
The main thing I disliked (hated) about NGRX/Entity was the way the single global state of entities continued to grow over the lifetime of the application. 

```c#
// The global way of doing it, as seen in NGRX/Entity
public class AllEntitiesState
{
  public Entities<Company> Companies { get; set; } = new Entities<Company>(x => x.CompanyId);
  // Lots of other entity collections here
  public Entities<User> Users { get; set; } = new Entities<User>(x => x.Id);
  public Entities<UserGroup> UserGroups { get; set; } = new Entities<UserGroup>(x => x.Id);
}

public class AllEntitiesFeature: EntitiesFeature<AllEntitiesState> 
{
  // The property name on the global state
  public override string GetName() => "AllEntitiesState";
}
```

I propose to solve this by allowing the library consumer to define sub-sets of entities to hold collections for different tasks that the application can perform. For example, if the user is editing Users + UserGroups they would create a sub-set of entities like this

```c#
public class EditUsersAndGroupsEntitiesState
{
  public Entities<User> Users { get; set; } = new Entities<User>(x => x.Id);
  public Entities<UserGroup> UserGroups { get; set; } = new Entities<UserGroup>(x => x.Id);
}

public class EditUsersAndGroupsEntitiesFeature: EntitiesFeature<EditUsersAndGroupsEntitiesState> 
{
  // The property name on the global state
  public override string GetName() => "EditUsersAndGroupsEntities";
}
```

When the user navigates away from the task the Blazor app can clear down this state.

To further improve the memory efficiency I also propose a second parameter in the `Entities<T>` constructor. This second parameter would accept a filter expression that determines whether or not this `Entities<T>` collection should hold a reference to a specific entity being upserted via `UpsertEntityAction`.

This would be particularly useful in a situation such as a Dashboard's state that holds information on the user currently logged in so their name can be displayed on the screen. Ideally we want this state to react to entity state changes from `UpsertEntityAction` but we don't want long-living state to collect all Users that are loaded into the app when the user starts to edit users + user groups. 

```c#
// Entities state that only holds a sub-set of entity instances
public class DashboardEntitiesState
{
  public Entities<User> Users { get; set; } = new Entities<User>(x => x.Id, x => x.IsCurrentUser);
}

public class DashboardEntitiesFeature: EntitiesFeature<DashboardEntitiesState> 
{
  // The property name on the global state
  public override string GetName() => "DashboardEntities";
}
```

**Comment by psampaio** [comment]
One suggestion I would make is, should you move forward with this, please make it a different package that extends the base Fluxor. In my case, I'm looking into implementing something closer to Relay, so what you propose could clash with that.

**Comment by psampaio** [comment]
Here you go: https://facebook.github.io/relay/

It's meant to integrate with GraphQL backends. There's a couple of packages to support this:
https://github.com/graphql-dotnet/
Note that the dotnet client doesn't fully work in Blazor because of json.net issues
