### ISSUE TITLE
Blazor Server Side

### ISSUE THREAD

**Issue by alfkonee** [mrpmorris/blazor-fluxor#42]
Hello There I'd like to ask if this library works on Blazor in Server Side Mode??

Cus I'm trying to Dispatch and Action to Trigger an Effect in the App.cshtml but it doesn't seem to be working

Please help

**Comment by mrpmorris** [comment]
It works in server-side, but everyone will see the same instance of the store.

**Comment by mrpmorris** [comment]
This has now been fixed.
