### ISSUE TITLE
Question: Observable effects

### ISSUE THREAD

**Issue by psampaio** [mrpmorris/blazor-fluxor#43]
Just wanted to get your thoughts on changing/extending the effects to support reactive extensions. The way they are currently implemented make sense, but there are some cases where you need more control over what executes and how it executes. I was looking into this talk (https://www.youtube.com/watch?v=AslncyG8whg) and its site (https://redux-observable.js.org/) and was wondering if you have anything similar in mind.

I see leaving the effects as they are and maybe create a new middleware to support the epics. On the pro side, you'd still have the effects for simple cases. On the con side, you'd have two different ways to do roughly the same.

**Comment by Gaulomatic** [comment]
I like the simplicity of the current approach but for cases in which the subscriber is not a `BlazorComponent`, it's handy to have observables. I absolutely support the suggestion.

**Comment by Gaulomatic** [comment]
I created a [Gist](https://gist.github.com/Gaulomatic/a6280806413e8a04bab0abf2433780e9) for a middleware. Quick and dirty.

**Comment by psampaio** [comment]
Nice! What's your suggested usage? Injecting the IReactiveStore instead of the required state? How would you use IReactiveEffects?

Also, I take it your reference to BlazorComponent means that you would replace the this.StateHasChanged() would be replaced with the observables, right?

**Comment by mrpmorris** [comment]
@psampaio @Gaulomatic Is it okay to close this issue?

**Comment by Gaulomatic** [comment]
@mrpmorris Yes, of course. Maybe you consider this approach as a feature to be included since a good portion of people will probably come from NgRX. On the other hand, the custom middleware works just fine.

**Comment by mrpmorris** [comment]
Perhaps you could email me about it? mrpmorris@gmail.com

**Comment by asalvo** [comment]
@Gaulomatic Thanks for providing the gist, it's exactly what I needed. 

If anyone uses the Gist in the latest version of Fluxor (0.23.1), you have to change the DI registration from Singleton to Scoped in OptionsExtensions.

**Comment by Gaulomatic** [comment]
@asalvo Thanks for the reminder, I've updated the Gist.

**Comment by mrpmorris** [comment]
@Gaulomatic I'd still like to discuss this with you. I did have plans to implement Rx as an additional package, but how would a BlazorComponent know the state has changed when a subscriber is updated?

**Comment by Gaulomatic** [comment]
@mrpmorris If a subscriber wants to alter the application state, it has to also dispatch an action which then in turn gets reflected in the store and component. Did I unerstand your question correctly or am I missing something? I was living under a rock for the last couple of months and I am just getting back to Blazor currently, so excuse me.

**Comment by mrpmorris** [comment]
@Gaulomatic 
1: Client dispatches a message
2: Reducer alters state
3: Middleware triggers Rx notifications

Are you subscribing to those streams in order to update the UI? If so, then how are you triggering StateHasChanged via the subscription when the value changes?

**Comment by Gaulomatic** [comment]
Something like this works:

```csharp
protected override void OnInit()
{
	this.Effects.Actions

		.TakeUntil(this._IsDisposed)
		.Where(action => action is OpenMobileSidebarAction)
		.Where(action => ((OpenMobileSidebarAction) action).SidebarPosition == this.SidebarPosition)
		.Subscribe(action =>
		{
			this._IsFullScreen = this._IsMobile;
			base.StateHasChanged();
		});

	this.Effects.Actions

		.TakeUntil(this._IsDisposed)
		.Where(action => action is CloseMobileSidebarAction)
		.Where(action => ((CloseMobileSidebarAction) action).SidebarPosition == this.SidebarPosition)
		.Subscribe(action =>
		{
			this._IsFullScreen = false;
			base.StateHasChanged();
		});
}
```

The same behavior can be achieved by this:

```csharp
protected override void OnInit()
{
	this.SidebarsState.Subscribe(this);
}

protected Boolean IsFullScreen
{
	get
	{
		if (!this._IsMobile)
		{
			return this._IsFullScreen;
		}

		if (this.SidebarsState.Value.Sidebars.ContainsKey(this.SidebarPosition) && this.SidebarsState.Value.Sidebars[this.SidebarPosition].IsOpen)
		{
			return this._IsMobile;
		}

		return false;
	}
	set => this._IsFullScreen = value;
}
```

Like I said to @psampaio, in a component the Rx style is not really going to help: You have to listen to specific action rather than to state changes alone (what if somethin else changes the state you are ultimativly interessted in?).

In NgRX the whole store is represented as an observable. That's why you have to use the `async` pipe in the Angular's HTML (which resolves the value):

```html
<h1>{{ IsOpen | async }}</h1>
```

**Comment by Gaulomatic** [comment]
I published a repo for the middleware:
https://github.com/Gaulomatic/Logixware.Web.Blazor.Fluxor

**Comment by mrpmorris** [comment]
Thanks @Gaulomatic 

I want to add Rx, but I wasn't very happy with the amount of code required to subscribe etc. I'd like to do something more inline with how RxUnity works. 

> this.SomeState.TakeUntilDisposed(this).NotifyStateHasChanged(this).Subscribe();

I can do the NotifyStateHasChanged part already, but the TakeUntilDisposed(this) would require a Disposed event on BaseComponent.

**Comment by Gaulomatic** [comment]
@mrpmorris I agree, Rx can get out of control at times - looking at you, Angular. I personally prefer the way Fluxor does it - it's more convinient and readable in most cases. However, there are some edge cases where I need to Rx my way through Blazor. Currently, I am working on an authorization system - which is really not that intuitive since you can observe the router sufficiently nor implement your own (correct me if I am wrong). In this case Observables come in pretty handy.

**Comment by mrpmorris** [comment]
Fluxor has a routing middleware here https://github.com/mrpmorris/blazor-fluxor/tree/master/src/Blazor.Fluxor/Routing

You can see how to enable it from line 9 in this sample https://github.com/mrpmorris/blazor-fluxor/blob/master/samples/03-ReduxDevToolsIntegration/ReduxDevToolsIntegration/ReduxDevToolsIntegration.Client/Startup.cs

Let me know if this is not sufficient for your needs.

**Comment by mrpmorris** [comment]
Note: Requested a Disposed event on ComponentBase
https://github.com/aspnet/AspNetCore/issues/10647

**Comment by Gaulomatic** [comment]
@mrpmorris Hey Peter, I agree with. The subscribe poiler plate code is anoying for human eyes. Huge and cumbersome. But it solves one aspect which the conventional event pattern lacks: async/await.

```csharp
store.States

	.TakeUntil(this.SkyNetRules)
	.Take<WorldDominationState>()
	.Select(newState => newState.IsSkyNetBooted)
	.DistinctUntilChanged()
	.Select(isBooted => Observable.FromAsync(async () =>
	{
		if (!isBooted)
			await this.BootSkyNet();
	}))
	.Concat() // or .Merge()
	.Subscribe();
```
