### ISSUE TITLE
Routing Middleware Info

### ISSUE THREAD

**Issue by TheFirstLairron** [mrpmorris/blazor-fluxor#46]
I noticed that a routing middleware exists in this library but there isn't any real info on it here. What information does this middleware provide? Is this a fully fledged middleware or just a debugging tool?

**Comment by mrpmorris** [comment]
It is possible to dispatch `Go` actions to change the URL, it is also possible to time-travel using the Redux Devtools extension for Chrome which will re-enact URL navigations.
If you have any more questions you can get hold of me on Twitter @mrpmorris
