### ISSUE TITLE
Question: Firing event when state has changed?

### ISSUE THREAD

**Issue by DerekChasse** [mrpmorris/blazor-fluxor#49]
I saw issue #43 and wanted to start another discussion about it.

I have a situation where I am storing notifications in my state.

I'm using a Material Snackbar and need to call a `.Show()` method when I want to display this notification.

Is there a way to come back to the component and invoke a method when state has changed?

I see the gist mentioned in the bug.  Is that the recommended way to achieve this?

**Comment by mrpmorris** [comment]
Sorry for the late reply.
If it's component rendering state you should store the last known value in a property in the component. When StateHasChanged is called you can check if it has changed, and if it has then update the last known value and call Show()
