### ISSUE TITLE
What is the definition of Feature

### ISSUE THREAD

**Issue by ahmadalibaloch** [mrpmorris/blazor-fluxor#57]
```
using Blazor.Fluxor;

namespace CounterSample.Client.Store.Counter
{
	public class CounterFeature : Feature<CounterState>
	{
		public override string GetName() => "Counter";
		protected override CounterState GetInitialState() => new CounterState(0);
	}
}
```

In the design of Flux or flow of events and information, where does the Feature stand? If we compare to React Flux or Redux what is the Feature?

**Comment by mrpmorris** [comment]
They are equivalent to StoreModule.forRoot feature modules.

See here. It shows "Starships" and "auth" as different modules.
https://www.intertech.com/Blog/ngrx-tutorial-add-state-to-feature-module/
