### ISSUE TITLE
How can I load initial state from LocalStorage

### ISSUE THREAD

**Issue by ahmadalibaloch** [mrpmorris/blazor-fluxor#59]
What is the good practice? Should I load local storage state on MainLayout.razor and create the State classes?

Or Is there some other way I can access local storage or razor services directly in State classes?

**Comment by mrpmorris** [comment]
IFeature.RestoreState will take an object of the correct type.

There is also some code in the ReduxDevTools middleware that restores all states of all features based on some JSON.

https://github.com/mrpmorris/blazor-fluxor/blob/96443a255492f9f2b47b4dcd701450d1f78d37b1/src/Blazor.Fluxor/ReduxDevTools/ReduxDevToolsMiddleware.cs#L69
