### ISSUE TITLE
Counter is not incrementing

### ISSUE THREAD

**Issue by dotnettrainingacademy** [mrpmorris/blazor-fluxor#63]
- Downloaded the nuget package

- Then Configured in startup.cs

- Added stores and actions but when I click the counter button it's not incrementing and not at showing any error

**Comment by brettcoburn** [comment]
Not the author but I was having a similar issue; you may have an out-of-date Nuget package. Try updating to 0.24 which (just released) and see if that helps.

**Comment by sachpatel** [comment]
@dotnettrainingacademy which version of the package are you using and are you using Visual Studio/VS Code?

Are you using dotnet core 3.0 and the latest Blazor project templates preview 6?

Changes in recent version of Blazor you might want to look out for that might be the actual cause of clicks not happening could be the change from `@function { }` declarations in your razor page that now need to be `@code {}` declarations. You should be able to breakpoint debug into the IncrementCounter function etc.

**Comment by gnamse** [comment]
Expiriencing the same issue as @dotnettrainingacademy

**Comment by mrpmorris** [comment]
Can someone upload a project that exhibits the problem?

**Comment by gnamse** [comment]
Please see example project

[ASP.NETCoreWebApplication.zip](https://github.com/mrpmorris/blazor-fluxor/files/3350695/ASP.NETCoreWebApplication.zip)

**Comment by mrpmorris** [comment]
Thanks for the example project. It seems you've missed a step. Read "Initializing the store" in this tutorial.

https://github.com/mrpmorris/blazor-fluxor/tree/master/samples/01-CounterSample
