### ISSUE TITLE
Support for preview6 - publish 0.24 on nuget.org

### ISSUE THREAD

**Issue by dradovic** [mrpmorris/blazor-fluxor#64]
I see you already have a commit about a release 0.24. Any idea when this will be available on nuget?

**Comment by dradovic** [comment]
In order to build a project that uses blazor-fluxor in a CI environment, we need the latest package to be available on nuget.org.

I would be great if you could publish 0.24 on nuget.org. Otherwise, I'm required to fork your project just to publish an "Unofficial" release of blazor-fluxor (which kind of pollutes the nuget repository IMHO).

**Comment by brettcoburn** [comment]
I was having the same issue. Looks like 0.24 was just released!

**Comment by dradovic** [comment]
Awesome!
