### ISSUE TITLE
Feature Request: Add a sample project with unit tests

### ISSUE THREAD

**Issue by amithegde** [mrpmorris/blazor-fluxor#68]
Having a sample with unit tests will set a pattern for having tests for the UI part.

**Comment by mrpmorris** [comment]
Unit testing the store is very simple as it is mostly pure functions (reducers).

Do you want a full integration test? I've not yet looked into integration testing in Blazor.

**Comment by amithegde** [comment]
yes, integration tests will be helpful as well

**Comment by mrpmorris** [comment]
This project is has been superseded by [Fluxor](https://github.com/mrpmorris/fluxor).
