### ISSUE TITLE
Weather Forecast Example in Preview 8

### ISSUE THREAD

**Issue by andrewwilkin** [mrpmorris/blazor-fluxor#72]
Apologies in advance, am trying to learn how to use this early on in a re-write of an existing app.

Tried following the tutorial along for the second example of fetch data. I see the page load but then nothing, can see the OnInitialized method is being called.

I cannot see the API end point being hit so something definitely not right. Cannot for the life of me see where I'm going wrong.

The readme references OnInitializedAsync yet the code used OnInitialized. is this definitely working in Preview 8? How do I trace things through?

**Comment by andrewwilkin** [comment]
I can trace it as far as the GetForecastDataAction being created, but then the code in GetForecastDataEffect never seems to be run.

Am trying to use it alongside authentication so maybe this is having a side effect (pardon the pun).

**Comment by andrewwilkin** [comment]
Tried following the example in a brand new project and cannot get it working. Have I missed something in how the scan of assembly is supposed to work with this:

`
services.AddFluxor(options =>
                options.UseDependencyInjection(typeof(Startup).Assembly)
            );
`

**Comment by DNF-SaS** [comment]
You have to manually initialize the store (e.g. in MainLayout):

    @inject Blazor.Fluxor.IStore Store
    @this.Store.Initialize()

**Comment by andrewwilkin** [comment]
Thanks, was feeling somewhat stupid as new it had to be simple.

Quick question if I may, if I want the store to survive across page navigation, e.g. load the first time I go to the fetch data end page but survive if I navigate away, is there best practice for doing this or should I simply make the store attached to higher level component?

**Comment by DNF-SaS** [comment]
@andrewwilkin no problem, I'm also a bloody newbie in terms of flux(or).
Somewhere was written that the store should be attached as near to the application's-root (of the component-hierarchy) as possible. It's just an information that sounds legit for me - cannot say any practical pros/contras.

**Comment by andrewwilkin** [comment]
Thanks will have a play 👍

**Comment by xperiandri** [comment]
Why not put initialization call to `App.razor`?
