### ISSUE TITLE
Console Errors in Blazor Server Side

### ISSUE THREAD

**Issue by andrevlins** [mrpmorris/blazor-fluxor#74]
Hi,

Just setting up a basic fluxor hello world with Blazor Server Side i got this errors in console:

![fluxor](https://user-images.githubusercontent.com/5325718/63479915-60211580-c466-11e9-97a6-0d48d71e0b6d.png)

The app runs fine and fluxor appears to work but I don't know the impact of this errors.

**Comment by andrevlins** [comment]
In addition to these errors, there is another thread context-related error that prevents using BLAZOR SERVER SIDE.

But if you disable prerendering all those errors are gone and the library works great.

**Comment by andrevlins** [comment]
Sorry, closed by mistake

**Comment by mrpmorris** [comment]
Can you provide a project that reproduces this problem? I'm not seeing it.

**Comment by andrevlins** [comment]
https://github.com/andrevlins/blazor-fluxor-issue-74

- Visual Studio 2019 Preview 16.3.0 Preview 2.0
- .Net Core 3.0.0-preview8-013656
- New Project -> Blazor App -> Create -> Blazor Server App

Added to Startup.cs:

`services.AddFluxor(options => options
                .UseDependencyInjection(typeof(Startup).Assembly)
                .AddMiddleware<Blazor.Fluxor.ReduxDevTools.ReduxDevToolsMiddleware>()
                .AddMiddleware<Blazor.Fluxor.Routing.RoutingMiddleware>()
            );
`

Added to MainLayout.razor:

`
@inject Blazor.Fluxor.IStore Store
@Store.Initialize()
`

F5 to start debugging then the errors are showed in Console tab of Chrome.
