### ISSUE TITLE
Having interfaces like IEffect and IReducer with 1 useful method is excesive

### ISSUE THREAD

**Issue by xperiandri** [mrpmorris/blazor-fluxor#76]
It would be better to just have Effect and Reducer attributes that you can apply to a static method.
Then you can match a method by Action type parameter and injecting all the required parameters from DI.
It would be much simpler to express, less code and easier to define in F#

**Comment by mrpmorris** [comment]
Have you tried implementing more than one interface on a single class? Would that suffice?

**Comment by mrpmorris** [comment]
You can implement IReducer<TState> on a class and it will receive a notification for all actions against that state.

https://github.com/mrpmorris/blazor-fluxor/blob/master/src/Blazor.Fluxor/IReducer.cs

**Comment by mrpmorris** [comment]
I've added a new `MultiActionReducer<TState>` to help with this scenario.

https://github.com/mrpmorris/blazor-fluxor/tree/master/samples/06-MultiActionReducerSample

**Comment by xperiandri** [comment]
Thanks, `MultiActionReducer` is a more convenient option for your vision of the project organization.
However, in the case of F# single reducer function per all states, it does not solve my issue.

I have state and action as discriminated unions (subclasses in C#). And a single reducer and a single effect handler with match (switch in C#).
If I could get rid of `namespace Project.Store.Fluxor` section it would be very beneficial
``` F#
namespace Project.Patient

open Project.Authentication
open Project.Authentication.SignIn
open Project.Constants
open Project.Store.Models
open System
open System.ComponentModel.DataAnnotations
open System.Net.Http
open System.Text
open System.Text.Json
open System.Text.Json.Serialization
open Microsoft.AspNetCore.Components
open Blazor.Fluxor

module SignUp =

    type State =
        | Initial
        | SignigUp
        | SignUpError of Error : string

    type Feature () =
        inherit Feature<State> ()
        override __.GetName () = "SignUp"
        override __.GetInitialState () = Initial

    [<CLIMutable>]
    type Data =
        {
            [<Required>]
            FirstName : string
            [<Required>]
            LastName : string
            [<Required; JsonPropertyName("EmailAddress")>]
            Email : string
            [<Required>]
            Password : string
        }

    type Action =
        | SignUp of Data : Data * RedirectUri : Uri
        | ProcessSignUpResult of Result : Result<SignIn.Data * Uri, string>

    let reduce action =
        match action with
        | SignUp _ -> SignigUp
        | ProcessSignUpResult (Ok (_, _)) -> Initial
        | ProcessSignUpResult (Error message) -> SignUpError message

    let execute (httpClient : HttpClient) (signUpData : Data, redirectUri : Uri) =
        System.Console.WriteLine("Sign Up")
        async {
            try
                let body = JsonSerializer.Serialize(signUpData, Json.options)
                System.Console.WriteLine(body)
                let content = new StringContent(body, Encoding.UTF8, "application/json")
                let! response = httpClient.PostAsync (Api.Patient.signUp, content, Async.DefaultCancellationToken)
                let! message = response.Content.ReadAsStringAsync ()
                System.Console.WriteLine(message)
                //do! HttpClientJsonExtensions.PostJsonAsync(httpClient, Api.Security.loginUser, signInData)
                return Ok ({Email= signUpData.Email; Password= signUpData.Password; KeepSignedIn= true}, redirectUri)
            with e ->
                System.Console.WriteLine(e)
                return Error e.Message
        }

namespace Project.Store.Fluxor
open Project
open Project.Authentication
open Project.Authentication.SignIn
open Project.Patient
open Project.Patient.SignUp
open System.Net.Http
open System.Threading.Tasks
open Blazor.Fluxor
open Blazor.Fluxor.Routing

type SignUpReducer () =
    inherit Reducer<Authentication.State, SignIn.Action>()
    override __.Reduce (state, action) =
        System.Console.WriteLine("Reducing action {0}", action);
        SignIn.reduce action

type SignUpEffect (httpClient : HttpClient) =
    inherit Effect<SignUp.Action> ()
    override __.HandleAsync (action, dispatcher) =
        System.Console.WriteLine("Handled");
        async {
            let! nextAction = async {
                match action with
                | SignUp (signUpData, redirectUri) ->
                    let! result = SignUp.execute httpClient (signUpData, redirectUri)
                    return ProcessSignUpResult result :> obj
                | ProcessSignUpResult (Ok (signInData, redirectUri)) ->
                    return SignIn (signInData, redirectUri) :> obj
                | ProcessSignUpResult (Error _) ->
                    return () :> obj
            }
            System.Console.WriteLine("Dispatching {0}", nextAction);
            dispatcher.Dispatch nextAction
        }
        |> Async.StartAsTask :> Task
```

**Comment by mrpmorris** [comment]
The IReducer is a generic interface `TState`, with a single Reduce method that takes `TState state, object action`

As for the reducer part of your problem, would using that instead of `Reducer<TState, TAction>` solve your problem?

**Comment by xperiandri** [comment]
Well, what I need is a general implementation of `IReducer` similar to `MultiActionReducer<TState>` which discovers reducers automatically. And the same thing for `IEffect`.

By the way, thanks for `MultiActionReducer<TState>`. I've just used for some non trivial case

**Comment by mrpmorris** [comment]
IEffects are triggered by action type. The only way to handle every action type is to write some middleware and plug that in.

MultiActionReducer is automatically discovered - the only limitation on it is that it can only work on a single state type. Is that not sufficient?

**Comment by xperiandri** [comment]
Well, it requires a lot of boilerplate for each action without such middleware.
I would prefer to mark reducer function (method) with `ReducerAttribute` and effect function (method) with `EffectAttribute`.
This way it will add a single line of code per method instead of 18 effective lines in my example.

**Comment by mrpmorris** [comment]
Was the MultiActionReducer suitable? It should be possible to create a MultiActionEffect class too (although I dislike that name so would want something better).

It would require associating the actions/effects in the constructor (like MultiActionReducer does).

**Comment by xperiandri** [comment]
> Was the MultiActionReducer suitable?

Yes, but it is not a full solution I expect

As now I have app authentication and user authentication I use it to handle two types of actions related to them
``` F#
type SignInReducer () =
    inherit MultiActionReducer<Authentication.State>()
    do base.AddActionReducer<SignInApplication.Action>(
        fun state action -> Application <| SignInApplication.reduce action)
    do base.AddActionReducer<SignInUser.Action>(
        fun state action -> User <| SignInUser.reduce action)

module SignInApplication =

    type State =
        | SigningIn
        | SignedIn of AccessToken : string
        | SignInError of Error : string

    type Action =
        | SignIn
        | ProcessSignInResult of Result : Result<string, string>

module SignInUser =

    type State =
        | SigningOut
        | SignOutError of Error : string
        | SigningIn
        | SignedIn of AccessToken : string * Data : UserData
        | SignInError of Error : string

    type Action =
        | SignIn of Data : Data * RedirectUri : Uri
        | ProcessSignInResult of Result : Result<string * UserData * Uri, string>
```

`MultiActionReducer` helped to eliminate a few lines of code, and I like that.

However, as I said earlier I would prefere not to implement any interface or derive from any class.
This does not have any usefulness in it. Just boilerplate code. Because at the end I have to store that classes somwhere and change them if somthing changes. But I only need a single method or a few methods. And to mark something for discovery in .NET we have an excellent mechanism of attributes.

**Comment by mrpmorris** [comment]
Writing in method discovery isn't something I have any plans to do. I don't see what is wrong with your `type SignInReducer`.

How would you expect to write that instead?

**Comment by xperiandri** [comment]
``` F#
module MyClass

[<Reducer>]
let reduce (state : MyState) (action : MyAction) = ...

[<Effect>]
let handle (effect : MyEffect) = ...
```

**Comment by mrpmorris** [comment]
That looks pretty simple, I think I'll do it.  The attributes will be named `ReducerAttribute` and `EffectHandlerAttribute`

```
[Reducer]
public MyState AnyNameWillDo(MyState state, object action) => .....;

[EffectHandler]
public Task<IEnumerable<Object>> AnyOtherNameWillDo(object effect) => .....;
```

The result of the event handler will be considered actions to dispatch once the handler is complete.  `null` will mean "Don't dispatch anything" - as will an empty enumerable (obviously).

How does that sound?

**Comment by xperiandri** [comment]
Looks great
Bear in mind that in F# nothing is expressed via subclass of class `Microsoft.FSharp.Core.FSharpOption<T>` where the singleton instance retrieved from `None` property means nothing and via an instance of structure `Microsoft.FSharp.Core.FSharpValueOption<T>`.
If it is possible to handle this case (even with a separate package) it would be nice. I mean some extensibility mechanism in your implementation of handlers and reducers execution.

**Comment by mrpmorris** [comment]
The whole approach has had to change to accommodate this. So far I have implemented `[Effect]`, `[Reducer]` is next.

```
// You can have static methods as effects
public static class MyEffects
{
	[Effect]
	public static Task HandleAsync(SomeAction action, IDispatcher dispatcher) { ..... }

	[Effect]
	public static Task HandleAsync(SomeAction2 action, IDispatcher dispatcher) { ..... }

	[Effect]
	public static Task HandleAsync(SomeAction3 action, IDispatcher dispatcher) { ..... }
}


// You will need instance methods when you need dependencies injected, but can still have multiple handlers per class
public class MyEffectWithDependencies
{
	private readonly HttpClient HttpClient;

	public MyEffectWithDependencies(HttpClient httpClient)
	{
		HttpClient = httpClient;
	}

	[Effect]
	public async Task HandleAsync(GetForecastDataAction action, IDispatcher dispatcher)
	{
		try
		{
			WeatherForecast[] forecasts =
				await HttpClient.GetJsonAsync<WeatherForecast[]>("api/SampleData/WeatherForecasts");
			dispatcher.Dispatch(new GetForecastDataCompletedAction(forecasts));
		}
		catch (Exception e)
		{
			dispatcher.Dispatch(new GetForecastDataCompletedAction(errorMessage: e.Message));
		}
	}
}
```

**Comment by xperiandri** [comment]
As you inject IDispatcher, can't you just inject other method's parameters if any?

**Comment by mrpmorris** [comment]
Possibly in a future update, but not this one.

Take a look at
https://github.com/mrpmorris/blazor-fluxor/blob/ChangeReducersToFunctions/samples/05-FlightFinder/FlightFinder/FlightFinder.Client/Store/Effects.cs

and
https://github.com/mrpmorris/blazor-fluxor/blob/ChangeReducersToFunctions/samples/05-FlightFinder/FlightFinder/FlightFinder.Client/Store/Reducers.cs

Let me know what you think.

**Comment by xperiandri** [comment]
Yep, looks very good! I will try to use

**Comment by mrpmorris** [comment]
Added `[ReducerMethod]` and '[EffectMethod]'

You can inject dependencies into the class.

**Comment by xperiandri** [comment]
OK
I think it is better to specify the action type on attribute instead of trying to deduce it from the method signature.
What do you think?

**Comment by mrpmorris** [comment]
No, because it might not match, and on reducers it might not match.
Are you having problems with it?

**Comment by xperiandri** [comment]
Well, this way you require exact order of parameters
I will show you my updated implementation

**Comment by mrpmorris** [comment]
Why would being able to specify the parameters in another order make sense, or be useful?
