### ISSUE TITLE
Unable to inject IState<MyState> in server side blazor project

### ISSUE THREAD

**Issue by NeilBumford** [mrpmorris/blazor-fluxor#79]
Hi,
I'm following the readme for 01-CounterSample. When I attempt to open a component that injects IState<MyState> I get this error:

Unable to resolve service for type 'Blazor.Fluxor.IFeature`1[BlazorOne.Store.Profile.ProfileState]' while attempting to activate 'Blazor.Fluxor.State`1[BlazorOne.Store.Profile.ProfileState]'.

Will this implementation work server-side?

**Comment by mrpmorris** [comment]
Yes, it works fine server-side.

Would you like to upload the source somewhere for me to have a look?

**Comment by NeilBumford** [comment]
Most kind.
I won't be able to this until I'm back at work tomorrow. What time zone are you in?

**Comment by mrpmorris** [comment]
UK

**Comment by NeilBumford** [comment]
[https://github.com/NeilBumford/borwell-blazor-fluxor-implementation](url)

Errors here: BlazorOne/Libs/Profile/Editor/Edit.Razor.cs (the one that really needs to work)
&: BlazorOne/Pages/Profile/Edit.razor

Thanks.

**Comment by mrpmorris** [comment]
Hi Neil

I can't get that to build.

**Comment by NeilBumford** [comment]
Ah, I'll sort this out first thing tomorrow.

**Comment by NeilBumford** [comment]
OK, I know what this is, I'll fix this tomorrow.

**Comment by NeilBumford** [comment]
Hi Pete.

That's fixed.

**Comment by mrpmorris** [comment]
Getting this now

```
D:\temp\borwell-blazor-fluxor-implementation\BlazorOne.Core>dotnet ef database update
System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
```

Can you send me a backup of a blank DB, or disable the requirement for a DB?

**Comment by NeilBumford** [comment]
There's a db migration all ready to go. You 'should' be able to do an 'Update-Database' in the Package Manager Console once you've done a build.

**Comment by NeilBumford** [comment]
Hi Pete,
FYI I've just tried to run CounterSample in VS version 16.3.0 Preview 2.0 . Here's the browser console output

HTML1300: Navigation occurred.
localhost:39853 (1,1)

CSS3121: The media query -ms-viewport has been deprecated.

WASM: ﻿System.AggregateException: One or more errors occurred. (VTable setup of type System.Text.Json.Utf8JsonWriter failed) ---> System.TypeLoadException: VTable setup of type System.Text.Json.Utf8JsonWriter failed

WASM:   at System.Text.Json.JsonSerializer.WriteCoreString (System.Object value, System.Type type, System.Text.Json.JsonSerializerOptions options) <0x1ce2680 + 0x00040> in <81a388037f1e4d689d9e115f9e29289e>:0 

WASM:   at System.Text.Json.JsonSerializer.ToStringInternal (System.Object value, System.Type type, System.Text.Json.JsonSerializerOptions options) <0x1ce2298 + 0x0000c> in <81a388037f1e4d689d9e115f9e29289e>:0 

WASM:   at System.Text.Json.JsonSerializer.Serialize[TValue] (TValue value, System.Text.Json.JsonSerializerOptions options) <0x1ce21d8 + 0x0000c> in <81a388037f1e4d689d9e115f9e29289e>:0 

WASM:   at Microsoft.JSInterop.JSInProcessRuntimeBase.Invoke[TValue] (System.String identifier, System.Object[] args) <0x1cc56c0 + 0x00014> in <30781c3ac5104a4783ec7e7411267cbe>:0 

WASM:   at Microsoft.AspNetCore.Blazor.Rendering.WebAssemblyRenderer.AddComponentAsync (System.Type componentType, System.String domElementSelector) <0x1c7d740 + 0x00066> in <1dd705d10aa5496ca9eea490dc558f6c>:0 

WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRendererAsync () <0x1c31e98 + 0x000dc> in <1dd705d10aa5496ca9eea490dc558f6c>:0 

WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsyncAwaited () <0x1c20af8 + 0x001f4> in <1dd705d10aa5496ca9eea490dc558f6c>:0 

WASM:    --- End of inner exception stack trace ---

WASM: ---> (Inner Exception #0) System.TypeLoadException: VTable setup of type System.Text.Json.Utf8JsonWriter failed

WASM:   at System.Text.Json.JsonSerializer.WriteCoreString (System.Object value, System.Type type, System.Text.Json.JsonSerializerOptions options) <0x1ce2680 + 0x00040> in <81a388037f1e4d689d9e115f9e29289e>:0 

WASM:   at System.Text.Json.JsonSerializer.ToStringInternal (System.Object value, System.Type type, System.Text.Json.JsonSerializerOptions options) <0x1ce2298 + 0x0000c> in <81a388037f1e4d689d9e115f9e29289e>:0 

WASM:   at System.Text.Json.JsonSerializer.Serialize[TValue] (TValue value, System.Text.Json.JsonSerializerOptions options) <0x1ce21d8 + 0x0000c> in <81a388037f1e4d689d9e115f9e29289e>:0 

WASM:   at Microsoft.JSInterop.JSInProcessRuntimeBase.Invoke[TValue] (System.String identifier, System.Object[] args) <0x1cc56c0 + 0x00014> in <30781c3ac5104a4783ec7e7411267cbe>:0 

WASM:   at Microsoft.AspNetCore.Blazor.Rendering.WebAssemblyRenderer.AddComponentAsync (System.Type componentType, System.String domElementSelector) <0x1c7d740 + 0x00066> in <1dd705d10aa5496ca9eea490dc558f6c>:0 

WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRendererAsync () <0x1c31e98 + 0x000dc> in <1dd705d10aa5496ca9eea490dc558f6c>:0 

WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsyncAwaited () <0x1c20af8 + 0x001f4> in <1dd705d10aa5496ca9eea490dc558f6c>:0 <---

WASM: 

Perhaps I should wait until you've upgraded the project?

**Comment by mrpmorris** [comment]
Are you saying this happens when you run Sample 01, unaltered?

I've just cloned the repo and run it and it worked fine (VS 16.3 Preview 2)

**Comment by NeilBumford** [comment]
Yes.
This may thicken the plot a little: Several of my colleagues have installed my repo without any issues and I did the same on my personal laptop.
I can make a version without a db but that's not guaranteed to resolve the issue, do you think?

**Comment by mrpmorris** [comment]
Hmm. That is peculiar, and does seem to hint at a problem with your setup.

Perhaps you have multiple versions of the SDK installed?

**Comment by NeilBumford** [comment]
I've cloned your latest repo and it's now working.

I'm still getting:
Error: System.InvalidOperationException: Unable to resolve service for type 'Blazor.Fluxor.IFeature`1[BlazorOne.Store.Profile.ProfileState]' while attempting to activate 'Blazor.Fluxor.State`1[BlazorOne.Store.Profile.ProfileState]'
in my project. Have you been able to take a look at it yet?

**Comment by mrpmorris** [comment]
I couldn't get your example to run, was unable to run "dotnet ef update database" (see above).

Can you switch your example to an in memory EF datastore instead of SQL?

**Comment by NeilBumford** [comment]
Open the Package Manager Console and do an Update-Database.

**Comment by NeilBumford** [comment]
I've replicated the issue in a new project. I had my store in a class library project. Is there any way to make that configuration work?

**Comment by mrpmorris** [comment]
https://github.com/NeilBumford/borwell-blazor-fluxor-implementation/blob/master/BlazorOne/Startup.cs#L39

Make sure you include all assemblies you want to reflect over for auto discovery of features etc.

**Comment by NeilBumford** [comment]
Tidy.

**Comment by mrpmorris** [comment]
Glad you got it resolved!
