### ISSUE TITLE
Too many namespace references

### ISSUE THREAD

**Issue by amithegde** [mrpmorris/blazor-fluxor#9]
I noticed that a simple page like counter has 3 namespace references. May be it's good idea to hide some of the namespaces to keep the clutter away.

**Comment by mrpmorris** [comment]
The samples now suggest the following structure

Store\FeatureName\ActionName

Into which you can put all your actions, effects, and reducers for that specific action. Now your page will only need `@using Store.FeatureName` for the state and `@using Store.FeatureName.ActionName` for each action you dispatch (obviously you can put them all into a single namespace if you wish).

This means you can press F12 on the action you create `await Store.DispatchAsync(new IncrementCounterAction())` and you will be taken to a folder that has all of the relevant code.

**Comment by mrpmorris** [comment]
In version 0.6.0-beta
