### ISSUE TITLE
Does ReduxDevToolsMiddleware work with Blazor Serverside?

### ISSUE THREAD

**Issue by DNF-SaS** [mrpmorris/blazor-fluxor#94]
No more text.

**Comment by mrpmorris** [comment]
It won't. In server-side apps the browser is simply a dumb terminal that sends user interactions to the server and receives HTML DOM updates. No store code is executed in the browser, and there is no browser on the server side to observe.

You could register an IMiddleware to log actions if you just want to see what is going on.
