### ISSUE TITLE
How to Get/Update single entity in State?

### ISSUE THREAD

**Issue by MitchellNZ** [mrpmorris/blazor-fluxor#95]
Firstly, thanks very much for this library! I'm pretty new to State Management, but I manged to get an example up and running within my own project pretty quickly.

I just have a couple of questions; 

**Setup**
I have followed your **02-WeatherForecastSample** to get a list of entities from my server (using effects, reducers, etc).

**Problem (Update)**
I have a "refresh" button on a detailed view of a single entity in the store, which causes the client to fetch just the 1 entity from the server.
I'm wondering if there is an example or "best practice" way to update an existing single entity?

**Problem (Get)**
On the detailed entity page, I need to access just the 1 entity from the store, rather than loop over them (like in the WeatherForecast sample). Again, I am wondering if there is a "best practice" way to access just this single entity? 
Currently, I have just written a "GetItem(string id)" method on my State, and call this in my components "OnInitialized" and again in "IState.StateChanged" event to trigger if updated while on the page.

I realize these are probably a lack of understanding rather than issue, sorry!

Thanks for your time.

**Comment by mrpmorris** [comment]
If I understand your problem correctly...

1. You have a list
2. You click on an item which reloads the single item from the server
3. You want the item in the list to refresh

If so, you can add a reducer method to your state like so

```
[ReducerMethod]
public static MyState (MyState state, GetSingleItemResponseFromServer action) =>
  new MyState(
    state.Items.Select(x => x.Id != action.Id
       ? x
       : new YourItemClass(id: action.Id, description: action.Description)
  );
```

**Comment by mrpmorris** [comment]
Does this answer your query?

**Comment by MitchellNZ** [comment]
Hi Peter, thanks very much for you reply, it has been very helpful!

Your understanding of my problem is pretty much correct, but I will be a bit more specific.

  1. List of items.
  2. Clicking an item navigates to item detail page and loads a single entity from the store.
  3. Clicking an "Update" button on the detail page triggers a refresh of the single entity (this refresh does some third-party calls and then updates the database with additional details).
  4. A SignalR response tells client the update has completed and sends back the updated entity.
  5. Using the method you have provided above, I have been able to update this single entity into my state.

As mentioned, the code sample you have provided is working well for my updates!

However, I still feel the way I am accessing the data to retrieve my single item when loading the detail page (point 2) could be improved.. or is not using the intended pattern.

I take your point about the detail page getting the freshest data from the server on load, and I agree. However, I am still wondering what your recommended way of accessing a single item from the state for display on the detail page would be.

If possible, could you provide another quick code example?

Hope this makes sense, and thanks again for your time, still trying to get my head into state management best practices.

**Comment by mrpmorris** [comment]
This is more a question of C# coding than state management.

As I said, I'd pass only the Id and load request it from the server in the dialog.

If you definitely want the exact state in the list then you can change the `@onclick` code on your list row's button button so it passes the object rather than object.id...

`<button @onclick=@( () => ShowDialog(currentItemFromForEachLoop)) >Edit</button>`

Blazor is C#, don't forget you can pass around object references :)

**Comment by MitchellNZ** [comment]
Okay great, just wanted to make sure there wasn't a state management recommend way to do this.

I played around with setting up a "CurrentItem" on my state and using Actions and Reducers to set that.. But it did seem over complicated.

Thanks very much for your help. 
Will close this issue now.

**Comment by mrpmorris** [comment]
Some people do go that far, but it makes for a lot of work.

I am more minimalist. I don't put forms etc into state. I only put stuff into state if it is a read-only display of existing data (because you never know how / when that might change).

I'll make an exception and add user input to state only if I want to allow them to switch to another page and then see the same input when they return.
