### ISSUE TITLE
Store Initialization failed on .NET Core 3.1 preview

### ISSUE THREAD

**Issue by hybrid-technologies-solutions** [mrpmorris/blazor-fluxor#98]
I know it's still preview, however, I could be good to prevent this issue to be real when .NET Core 3.1 will be RTM.

For testing, I have taken the CounterSample (and remove global.json btw), update it to .NET Core 3.1 (installing 3.1 preview 1 SDK), exception on launch

**Comment by hybrid-technologies-solutions** [comment]
Sure : 
```
Blazor.Fluxor.Exceptions.StoreInitializationException : 'Store initialization error'

Internal exception : JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

CallStack : This exception was originally thrown at this call stack:
	Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long, string, string)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	Blazor.Fluxor.JavaScriptStoreInitializationStrategy.Initialize.AnonymousMethod__0(object)

```

**Comment by mrpmorris** [comment]
Ahh. What is the class type of the inner exception please?

**Comment by gptucci** [comment]
Class JavaScriptStoreInitializationStrategy
Method: Initialize

**Comment by hybrid-technologies-solutions** [comment]
Thanks for answer gptucci !
@mrpmorris any idea when a release (even preview) can be available on Nuget ? I would love to upgrade to .NET Core 3.1 as soon as possible

**Comment by mrpmorris** [comment]
> Thanks for answer gptucci !
> @mrpmorris any idea when a release (even preview) can be available on Nuget ? I would love to upgrade to .NET Core 3.1 as soon as possible

I'll see if I can get a preview release out this weekend.

**Comment by mrpmorris** [comment]
Released a preview build

**Comment by CtrlAltNoot** [comment]
Sorry to re-open this on you, but I'm running into the exact same exception on my side. Server-Side blazor project. Store initialization failed.

**Comment by CtrlAltNoot** [comment]
Actually, weirdly enough if I removed the old NewtonsoftJson() piece in my startup, it fired right up! So... not sure what happened there but it works now. 😄

**Comment by mrpmorris** [comment]
You'll find you are missing app.UseStaticContent in Startup.cs which is preventing the Fluxor JavaScript from being sent to the browser. It's a breaking change in 3.1.

Add it just above app.UseClientSideBlazorFiles.

**Comment by Gaulomatic** [comment]
There is something wrong with the ReduxDevTools since 3.1. I am a little bit lost on this one but I suspect it has something to do with the changed initialization:

![image](https://user-images.githubusercontent.com/7631781/70467620-d86b1f80-1ac5-11ea-9553-c79e579fe9e0.png)

**Comment by mrpmorris** [comment]
It's working in the samples, could you compare the relevant files (startup.cs, index.html script order, etc)?

**Comment by Gaulomatic** [comment]
This is for Server Side, the script order is as follows:

- dynamic script from `IStore.Initialize()`
- `_framework/blazor.server.js`
- `_content/Blazor.Fluxor/index.js`

I did look into the examples before posting here, am I getting something wrong here? Nothing changed, I just upgraded to 3.1 and the latest Fluxor (from 1.0). I played around with the script order, but this made things worse most of the time.

**Comment by mrpmorris** [comment]
Can you cut the app down to the bare minimum to reproduce the problem and send it to me?

mrpmorris@gmail.com

**Comment by mrpmorris** [comment]
Thanks for the sample, I will get to this as soon as I can.

**Comment by VDKB** [comment]
Hi,

I've just tested Blazor-Fluxor to use it in our Blazor project and I did get the same error.

I then created a new Blazor application (Server-side) in Visual Studio and started there with the "Counter" example. I still got the same error.

I changed the nuget package from 1.1.0 to 1.0.0 and then it worked. There was an error because it can't find  `_content/Blazor.Fluxor/index.js`. But the counter value gets updated.

**Comment by mrpmorris** [comment]
Did you add that script to your _Host.cshtml file? Blazor no longer adds library resources automatically.

**Comment by VDKB** [comment]
Yes I did, just above the blazor.server script. This is the only error I get in version 1.0.0.

**Comment by mrpmorris** [comment]
Can we chat on https://gitter.im/aspnet/Blazor?

**Comment by mrpmorris** [comment]
@VDKB Could you try this branch? It should work...
https://github.com/mrpmorris/blazor-fluxor/tree/PeteM/98-CannotInitializeStore

**Comment by VDKB** [comment]
@mrpmorris I don't get any errors anymore.  Thanks!

**Comment by mrpmorris** [comment]
Thank you for letting me know!
